### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by gitttt** [eurecom-s3/vagrant#3]
I am not sure if the box was correctly setup. It hung at the end of the `vagrant up`.
Are the below failing tests the result of a half set-up box? Or are other problems causing the tests to fail?

```
login as: vagrant
vagrant@127.0.0.1's password:
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-83-generic x86_64)

vagrant@vagrant-ubuntu-trusty-64:~$ cd projects/news2e/test && make check
make -C tests build
make[1]: Entering directory `/home/vagrant/projects/news2e/test/tests'
for dir in arm thumb thumb2 ; do \
                make -C ${dir} build; \
        done
make[2]: Entering directory `/home/vagrant/projects/news2e/test/tests/arm'
for dir in hello_world tight_loop base_instructions_kill load_memory; do \
                make -C ${dir} build; \
        done
make[3]: Entering directory `/home/vagrant/projects/news2e/test/tests/arm/hello_                                                                                  world'
arm-none-eabi-gcc -I../../../../guest/include/   -c -o test.o test.c
arm-none-eabi-gcc -nostartfiles -nostdlib -Wl,-T test.ld  test.o   -o test
make[3]: Leaving directory `/home/vagrant/projects/news2e/test/tests/arm/hello_w                                                                                  orld'
make[3]: Entering directory `/home/vagrant/projects/news2e/test/tests/arm/tight_                                                                                  loop'
arm-none-eabi-gcc    -c -o test.o test.S
arm-none-eabi-gcc -nostartfiles -nostdlib  test.o   -o test
make[3]: Leaving directory `/home/vagrant/projects/news2e/test/tests/arm/tight_l                                                                                  oop'
make[3]: Entering directory `/home/vagrant/projects/news2e/test/tests/arm/base_i                                                                                  nstructions_kill'
arm-none-eabi-gcc -I../../../../guest/include/   -c -o test.o test.c
arm-none-eabi-gcc -nostartfiles -nostdlib  test.o   -o test
make[3]: Leaving directory `/home/vagrant/projects/news2e/test/tests/arm/base_in                                                                                  structions_kill'
make[3]: Entering directory `/home/vagrant/projects/news2e/test/tests/arm/load_m                                                                                  emory'
arm-none-eabi-gcc    -c -o test.o test.S
arm-none-eabi-gcc -nostartfiles -nostdlib  test.o   -o test
make[3]: Leaving directory `/home/vagrant/projects/news2e/test/tests/arm/load_me                                                                                  mory'
make[2]: Leaving directory `/home/vagrant/projects/news2e/test/tests/arm'
make[2]: Entering directory `/home/vagrant/projects/news2e/test/tests/thumb'
for dir in base_instructions_kill ; do \
                make -C ${dir} build; \
        done
make[3]: Entering directory `/home/vagrant/projects/news2e/test/tests/thumb/base                                                                                  _instructions_kill'
arm-none-eabi-gcc -I../../../../guest/include/ -mcpu=arm966e-s -mthumb   -c -o t                                                                                  est.o test.c
arm-none-eabi-gcc -I../../../../guest/include/ -mcpu=arm966e-s -marm   -c -o sta                                                                                  rt.o start.c
arm-none-eabi-gcc -nostartfiles -nostdlib  test.o start.o   -o test
make[3]: Leaving directory `/home/vagrant/projects/news2e/test/tests/thumb/base_                                                                                  instructions_kill'
make[2]: Leaving directory `/home/vagrant/projects/news2e/test/tests/thumb'
make[2]: Entering directory `/home/vagrant/projects/news2e/test/tests/thumb2'
for dir in base_instructions_kill ; do \
                make -C ${dir} build; \
        done
make[3]: Entering directory `/home/vagrant/projects/news2e/test/tests/thumb2/bas                                                                                  e_instructions_kill'
arm-none-eabi-gcc -I../../../../guest/include/ -mcpu=cortex-m3 -mthumb   -c -o t                                                                                  est.o test.c
arm-none-eabi-gcc -I../../../../guest/include/ -mcpu=cortex-m3 -mthumb   -c -o s                                                                                  tart.o start.c
arm-none-eabi-gcc -nostartfiles -nostdlib  test.o start.o   -o test
make[3]: Leaving directory `/home/vagrant/projects/news2e/test/tests/thumb2/base                                                                                  _instructions_kill'
make[2]: Leaving directory `/home/vagrant/projects/news2e/test/tests/thumb2'
make[1]: Leaving directory `/home/vagrant/projects/news2e/test/tests'
Feature: Check that the BaseInstructions kill opcode is working for the ARM inst                                                                                  ruction set

  Background:
    Given current test directory at "tests/arm/base_instructions_kill"
    Given S2E config file named "s2e_conf.lua"
    Given ARM firmware named "test"
    When S2E test is run for at most 60 seconds
      No such file or directory - /home/vagrant/projects/news2e-build/qemu-debug                                                                                  /arm-s2e-softmmu/qemu-system-arm (Aruba::LaunchError)
      /usr/lib/ruby/vendor_ruby/aruba/spawn_process.rb:32:in `rescue in run!'
      /usr/lib/ruby/vendor_ruby/aruba/spawn_process.rb:29:in `run!'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:303:in `block in run'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:13:in `chdir'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:13:in `in_current_dir'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:295:in `run'
      ./features/step_definitions/s2e.rb:35:in `/^S2E test is run for at most (\                                                                                  d+) seconds$/'
      features/arm_base_instructions_kill.feature:7:in `When S2E test is run for                                                                                   at most 60 seconds'

  Scenario: Check output for messages that the state was killed successfully
    Then the stdout should contain "[State 0] Killing state 0"
    And the stdout should contain "[State 0] State was terminated by opcode"
    And the stdout should contain "message: \"State killed OK\""

Feature: Check that the BaseInstructions kill opcode is working for the Thumb2 i                                                                                  nstruction set

  Background:
    Given current test directory at "tests/thumb2/base_instructions_kill"
    Given S2E config file named "s2e_conf.lua"
    Given ARM firmware named "test"
    When S2E test is run for at most 60 seconds
      No such file or directory - /home/vagrant/projects/news2e-build/qemu-debug                                                                                  /arm-s2e-softmmu/qemu-system-arm (Aruba::LaunchError)
      /usr/lib/ruby/vendor_ruby/aruba/spawn_process.rb:32:in `rescue in run!'
      /usr/lib/ruby/vendor_ruby/aruba/spawn_process.rb:29:in `run!'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:303:in `block in run'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:13:in `chdir'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:13:in `in_current_dir'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:295:in `run'
      ./features/step_definitions/s2e.rb:35:in `/^S2E test is run for at most (\                                                                                  d+) seconds$/'
      features/thumb2_base_instructions_kill.feature:7:in `When S2E test is run                                                                                   for at most 60 seconds'

  Scenario: Check output for messages that the state was killed successfully
    Then the stdout should contain "[State 0] Killing state 0"
    And the stdout should contain "[State 0] State was terminated by opcode"
    And the stdout should contain "message: \"State killed OK\""

Feature: Check that the BaseInstructions kill opcode is working for the Thumb in                                                                                  struction set

  Background:
    Given current test directory at "tests/thumb/base_instructions_kill"
    Given S2E config file named "s2e_conf.lua"
    Given ARM firmware named "test"
    When S2E test is run for at most 60 seconds
      No such file or directory - /home/vagrant/projects/news2e-build/qemu-debug                                                                                  /arm-s2e-softmmu/qemu-system-arm (Aruba::LaunchError)
      /usr/lib/ruby/vendor_ruby/aruba/spawn_process.rb:32:in `rescue in run!'
      /usr/lib/ruby/vendor_ruby/aruba/spawn_process.rb:29:in `run!'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:303:in `block in run'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:13:in `chdir'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:13:in `in_current_dir'
      /usr/lib/ruby/vendor_ruby/aruba/api.rb:295:in `run'
      ./features/step_definitions/s2e.rb:35:in `/^S2E test is run for at most (\                                                                                  d+) seconds$/'
      features/thumb_base_instructions_kill.feature:7:in `When S2E test is run f                                                                                  or at most 60 seconds'

  Scenario: Check output for messages that the state was killed successfully
    Then the stdout should contain "[State 0] Killing state 0"
    And the stdout should contain "[State 0] State was terminated by opcode"
    And the stdout should contain "message: \"State killed OK\""

Failing Scenarios:
cucumber features/arm_base_instructions_kill.feature:10
cucumber features/thumb2_base_instructions_kill.feature:10
cucumber features/thumb_base_instructions_kill.feature:10

3 scenarios (3 failed)
21 steps (3 failed, 9 skipped, 9 passed)
0m0.212s
make: *** [check] Error 1
```

**Comment by zaddach** [comment]
This looks like the release build of S2E is used, which is currently broken. I'm investigating the problem, but I'm not sure where it stems from. Check that the S2E_DIR environment variable points to the right path ("..../qemu-debug").
